###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

photocontainer-site-webserver:
  image: phpdockerio/nginx:latest
  container_name: photocontainer-site-webserver
  volumes:
      - ..:/var/www/photocontainer-site
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
  links:
   - photocontainer-site-php-fpm

photocontainer-site-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: photocontainer-site-php-fpm
  volumes:
    - ..:/var/www/photocontainer-site
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
